#Dataset and Loading Setting
DATASET: 'edges'
RANDOM_CROP: False
MASKFROMFILE: False
LOG_DIR: checlpoints_full_model_256
MODEL_RESTORE: '' #'201809200859_full_model_places2_256/epoch_1_ckpt.pth.tar'  # '20180115220926508503_jyugpu0_places2_NORMAL_wgan_gp_full_model'

#overall setting
GAN: 'sn_pgan'  # 'dcgan', 'lsgan', 'wgan_gp', 'one_wgan_gp'
PRETRAIN_COARSE_NETWORK: False
IMG_SHAPES: [256, 256]
BATCH_SIZE: 8
RANDOM_SEED: False
PADDING: 'SAME'
BATCH_NORM: False
# training
NUM_GPUS: 1
GPU_ID: 0  # -1 indicate select any available one, otherwise select gpu ID, e.g. [0,1,3]
EPOCH: 50
GRADS_SUMMARY: False
GRADIENT_CLIP: False
GRADIENT_CLIP_VALUE: 0.1
SUMMARY_FREQ: 50
VAL_SUMMARY_FREQ: 3200
LEARNING_RATE: 0.0001
WEIGHT_DECAY: 0.0

#validate
STATIC_VIEW_SIZE: 100

# loss
AE_LOSS: True
L1_LOSS: True
GLOBAL_DCGAN_LOSS_ALPHA: 1.
GLOBAL_WGAN_LOSS_ALPHA: 1.
GAN_LOSS_ALPHA: 0.005  # dcgan: 0.0008, wgan: 0.0005, onegan: 0.001
WGAN_GP_LAMBDA: 10
L1_LOSS_ALPHA: [1.2, 1.2, 1.2, 1.2]
GAN_WITH_MASK: True
GAN_WITH_GUIDE: False
DISCOUNTED_MASK: False

# loss legacy
LOAD_VGG_MODEL: False
FEATURE_LOSS: False
GRAMS_LOSS: False
TV_LOSS: False
TV_LOSS_ALPHA: 0.
FEATURE_LOSS_ALPHA: 0.01
GRAMS_LOSS_ALPHA: 50
SPATIAL_DISCOUNTING_GAMMA: 0.9

# data
DATA_FLIST:

  edges:
      base_path: '/root/fast_storage/datasets/face/MsCeleb_others/'
      train_fname: 'train.txt'
      test_fname: 'test.txt'
